import type { Category, Supplier, TenderConfig, TenderScenario } from "@/types/tender"

const heatPumpSuppliers: Supplier[] = [
  {
    id: "1",
    name: "Klimaservice Malte Born",
    logo: "/site elements/gogreen.svg",
    price: 45000,
    fields: {
      systemType: "Full fixture replacement",
      manufacturer: "OSRAM",
      numberOfLights: "2,494",
      installationCostsIncluded: "YES",
      replacementType: "New LED fixtures",
      labourAndOtherCosts: "156.573,32 €",
      materialCosts: "180.131,90 €",
      meetsTechnicalRequirements: "YES",
      meetsTenderRequirements: "YES",
      controlStrategyMeetsRegulations: "YES",
      emergencyLightingIncluded: "Installation",
      equipmentRemoval: "Yes",
      unitLocation: "Roof",
      electricalWork: "No",
      noiseControl: "Yes",
      operatingTemps: "Yes",
      romeCompliance: "TBC",
      romeCertification: "Not required",
      romeStandards: "Compliant",
    },
    additionalNotes: "Price includes an approximate price for lifting equipment",
    keyDifferentiator: "Price includes an approximate price for lifting equipment",
    documents: [
      { name: "Technical spec.pdf", url: "#" },
      { name: "Pricing breakdown.xlsx", url: "#" },
    ],
  },
  {
    id: "2",
    name: "Beka Solar Energie GmbH",
    logo: "/site elements/beba.svg",
    price: 52000,
    fields: {
      systemType: "Full fixture replacement",
      manufacturer: "LEDVANCE, EVN, Nobile, TEGCGET, Schuch, RZB, Philips",
      numberOfLights: "2,494",
      installationCostsIncluded: "YES",
      replacementType: "New LED fixtures",
      labourAndOtherCosts: "132.637,00 €",
      materialCosts: "163.937,05 €",
      meetsTechnicalRequirements: "YES",
      meetsTenderRequirements: "YES",
      controlStrategyMeetsRegulations: "YES",
      emergencyLightingIncluded: "Installation",
      equipmentRemoval: "Yes",
      unitLocation: "TBC: Roof / Outside",
      electricalWork: "Yes",
      noiseControl: "TBC on site visit",
      operatingTemps: "Yes",
      romeCompliance: "TBC",
      romeCertification: "Not required",
      romeStandards: "TBC",
    },
    additionalNotes:
      "Additional capacity in heat pump and electric immersion heater to minimise heating shortfall risk.",
    keyDifferentiator:
      "Additional capacity in heat pump and electric immersion heater to minimise heating shortfall risk.",
    documents: [
      { name: "Technical spec.pdf", url: "#" },
      { name: "Pricing breakdown.xlsx", url: "#" },
    ],
  },
  {
    id: "3",
    name: "Eco-Heat UG",
    logo: "/site elements/lowcarbon.svg",
    price: 48000,
    fields: {
      systemType: "Full fixture replacement",
      manufacturer: "GLT (their own product)",
      numberOfLights: "2,494",
      installationCostsIncluded: "NO",
      replacementType: "New LED fixtures",
      labourAndOtherCosts: "Approximately 160.000,00 €",
      materialCosts: "230.884,60 €",
      meetsTechnicalRequirements: "YES",
      meetsTenderRequirements: "NO",
      controlStrategyMeetsRegulations: "YES",
      emergencyLightingIncluded: "Design",
      equipmentRemoval: "Not required",
      unitLocation: "Courtyard",
      electricalWork: "Yes",
      noiseControl: "Yes based on analysis",
      operatingTemps: "Yes",
      romeCompliance: "Not required",
      romeCertification: "TBC",
      romeStandards: "Compliant",
    },
    additionalNotes: "Existing gas boilers retained to boost heat pump output if heat pumps fall short.",
    keyDifferentiator: "Existing gas boilers retained to boost heat pump output if heat pumps fall short.",
    documents: [
      { name: "Technical spec.pdf", url: "#" },
      { name: "Pricing breakdown.xlsx", url: "#" },
    ],
  },
  {
    id: "4",
    name: "Ecowatt GmbH",
    logo: "/site elements/hysopt.svg",
    price: 58000,
    fields: {
      systemType: "Full fixture replacement",
      manufacturer: "Philips, LEDVANCE, Beleuchtung Direkt, Dotlux",
      numberOfLights: "2,494",
      installationCostsIncluded: "YES",
      replacementType: "New LED fixtures",
      labourAndOtherCosts: "166.682,23 €",
      materialCosts: "103.607,47 €",
      meetsTechnicalRequirements: "YES",
      meetsTenderRequirements: "YES",
      controlStrategyMeetsRegulations: "YES",
      emergencyLightingIncluded: "Yes, included but only for central battery operation",
      equipmentRemoval: "Not required",
      unitLocation: "Outside",
      electricalWork: "Yes",
      noiseControl: "Yes",
      operatingTemps: "TBC",
      romeCompliance: "Compliant",
      romeCertification: "TBC",
      romeStandards: "Not required",
    },
    additionalNotes:
      "High allowance for design and planning. Could be reduced/negotiated if subsidy not required. High cost for balancing",
    keyDifferentiator:
      "High allowance for design and planning. Could be reduced/negotiated if subsidy not required. High cost for balancing",
    documents: [
      { name: "Technical spec.pdf", url: "#" },
      { name: "Pricing breakdown.xlsx", url: "#" },
    ],
  },
]

const heatPumpCategories: Category[] = [
  {
    name: "Scope",
    expanded: true,
    fields: [
      { label: "System type/ Scope", key: "systemType" },
      { label: "LED Lighting manufacture", key: "manufacturer" },
      { label: "Number of lights", key: "numberOfLights" },
    ],
  },
  {
    name: "Costs",
    expanded: true,
    fields: [
      { label: "Installation costs (included)", key: "installationCostsIncluded" },
      { label: "Bulb replacement/ New LED fixtures", key: "replacementType" },
      { label: "Labour costs+Other costs", key: "labourAndOtherCosts" },
      { label: "Material costs", key: "materialCosts" },
    ],
  },
  {
    name: "Compliance",
    expanded: true,
    fields: [
      { label: "Meets technical requirements", key: "meetsTechnicalRequirements" },
      { label: "Meets tender requirements", key: "meetsTenderRequirements" },
      { label: "Control strategy meets building regulations", key: "controlStrategyMeetsRegulations" },
      { label: "Emergency lighting - what's included?", key: "emergencyLightingIncluded" },
    ],
  },
  {
    name: "Rome",
    expanded: true,
    fields: [
      { label: "Rome compliance", key: "romeCompliance" },
      { label: "Rome certification", key: "romeCertification" },
      { label: "Rome standards", key: "romeStandards" },
    ],
  },
]

const heatPumpFieldExplanations: Record<string, string> = {
  systemType: "Proposed scope of works",
  manufacturer: "Manufacturers proposed for LED lighting",
  numberOfLights: "Count of fixtures in scope",
  installationCostsIncluded: "Whether installation costs are included",
  replacementType: "Whether bulbs or full fixtures are replaced",
  labourAndOtherCosts: "Quoted labour and miscellaneous costs",
  materialCosts: "Quoted materials costs",
  meetsTechnicalRequirements: "Compliance with technical requirements",
  meetsTenderRequirements: "Compliance with tender requirements",
  controlStrategyMeetsRegulations: "Control strategy compliance",
  emergencyLightingIncluded: "Items included within emergency lighting scope",
  romeCompliance: "Rome compliance statement",
  romeCertification: "Rome certification evidence",
  romeStandards: "Rome standards alignment",
}

const solarSuppliers: Supplier[] = [
  {
    id: "11",
    name: "HHT Group",
    logo: "/site elements/solar pv logos/HHT Group.png",
    price: 1417886,
    fields: {
      deliveryTime: "7",
      maintenanceTerm: "5",
      ppa: "Yes",
      leadTimeWeeks: "3",
      installationDays: "80",
      commissioningDays: "7",
      capexAvailable: "TRUE",
      capexUpfrontGBP: "1417886",
      capexAnnualGBP: "19728",
      capexMinTermYears: "5",
      hpAvailable: "TRUE",
      hpUpfrontGBP: "",
      hpAnnualGBP: "",
      hpTermYears: "",
      ppaAvailable: "TRUE",
      ppaUpfrontGBP: "0",
      ppaAnnualGBP: "0",
      ppaTermYears: "25",
      maintenancePriceGBP: "19729",
      oMApproach: "Our O&M is free of charge and included with the PPA. An additional cost is required for capex purchases. We have stated an initial timeframe of 5 years for paid O&M but this can be as long as the client wants it to be. PPA O&M is as long as the PPA agreement. Operations & Maintenance Services As both the owner and operator of the solar projects they fund, HHT Group provides: Annual Maintenance Services: Regular inspections and maintenance to ensure optimal performance of solar installations. Performance Monitoring: Utilization of advanced technologies, such as SolarEdge's DC-optimized systems, to monitor system performance in real-time, enabling rapid fault detection and maintenance. Long-Term Support: Ongoing support throughout the project's lifespan, including addressing concerns and optimizing system performance. Remote monitoring: 24/7 monitoring of the system performance via its online monitoring platform, allowing for instant identification of issues as they arise and a proactive approach to maintenance Priority support: in the event of any issues, priority access to our site team resources to resolve sooner and minimise downtime.",
      annualOutputkWh: "1340277",
      annualConsumptionkWh: "634449",
      selfSufficiencyPercent: "0",
      annualExportkWh: "705828",
      panelWarrantyYears: "25",
      inverterWarrantyYears: "10",
      workmanshipWarrantyYears: "1",
      systemLifetimeYears: "25",
    },
    additionalNotes: "",
    keyDifferentiator: "",
    documents: [
      { name: "HHT-technical-spec.pdf", url: "#" },
      { name: "HHT-costing.xlsx", url: "#" },
    ],
  },
  {
    id: "12",
    name: "SONNE Power",
    logo: "/site elements/solar pv logos/Sonne Test Supplier.png",
    price: 1301582.81,
    fields: {
      deliveryTime: "10",
      maintenanceTerm: "5",
      ppa: "No",
      leadTimeWeeks: "3",
      installationDays: "84",
      commissioningDays: "5",
      capexAvailable: "TRUE",
      capexUpfrontGBP: "1301582.81",
      capexAnnualGBP: "2750",
      capexMinTermYears: "5",
      hpAvailable: "FALSE",
      hpUpfrontGBP: "",
      hpAnnualGBP: "",
      hpTermYears: "",
      ppaAvailable: "FALSE",
      ppaUpfrontGBP: "",
      ppaAnnualGBP: "",
      ppaTermYears: "",
      maintenancePriceGBP: "2750",
      oMApproach: "Annual audit: a physical check of the full health of the system across all components. This includes inspection and testing of the electrical components to ensure system output is in line with expectations, inspection of the array and mounting to check for damage and ensure structural integrity, and a full thermography inspection of the system to identify any electrical issues before they arise. Services Included - Annual servicing: Catch any warning signs and prevent problems from developing. 24/7 remote system monitoring: Our office team monitor the performance of your system daily, reducing potential downtime. Technical: Telephone support and troubleshooting to resolve minor problems or errors. Quarterly and annual performance report: Provides an overview of your energy portfolio and any advisory actions. Maintenance and repairs: In case of a fault, our engineers will get you back up and running.",
      annualOutputkWh: "1470000",
      annualConsumptionkWh: "718000",
      selfSufficiencyPercent: "0",
      annualExportkWh: "752000",
      panelWarrantyYears: "25",
      inverterWarrantyYears: "20",
      workmanshipWarrantyYears: "2",
      systemLifetimeYears: "25",
    },
    additionalNotes: "",
    keyDifferentiator: "",
    documents: [
      { name: "SONNE-proposal.pdf", url: "#" },
      { name: "SONNE-schedule.xlsx", url: "#" },
    ],
  },
  {
    id: "13",
    name: "Carraldo Energy",
    logo: "/site elements/solar pv logos/Carraldo Test Supplier.png",
    price: 1151973,
    fields: {
      deliveryTime: "14",
      maintenanceTerm: "10",
      ppa: "No",
      leadTimeWeeks: "4",
      installationDays: "60",
      commissioningDays: "10",
      capexAvailable: "TRUE",
      capexUpfrontGBP: "1151973",
      capexAnnualGBP: "15000",
      capexMinTermYears: "10",
      hpAvailable: "FALSE",
      hpUpfrontGBP: "",
      hpAnnualGBP: "",
      hpTermYears: "",
      ppaAvailable: "FALSE",
      ppaUpfrontGBP: "",
      ppaAnnualGBP: "",
      ppaTermYears: "",
      maintenancePriceGBP: "15000",
      oMApproach: "Cleaning: If required, Our specialist solar panel cleaning service will be provided to improve the efficiency of the system. To ensure the long-term success and reliability of our solar PV systems, we implement a comprehensive approach to performance monitoring and post-installation support. This begins immediately after the system is commissioned, when we activate remote monitoring tools that continuously track the system's output. These tools allow us to compare real-time performance data against the expected generation levels defined in the design phase. If performance drops below guaranteed thresholds, alerts are triggered so issues can be promptly investigated and resolved. Our support doesn't end at handover. We schedule follow-up calls or site visits to verify the system's performance, answer any client questions, and address potential concerns. If a defect or performance issue arises, we have structured processes in place for identifying, documenting, and resolving faults. Clients are given straightforward procedures to report any issues, which are logged in our service management system. From there, a qualified service engineer is deployed to diagnose the problem using appropriate diagnostic tools. Once a defect is identified, a clear rectification plan is created and shared with the client. Repairs are executed by certified technicians, and each fix is followed by testing to verify successful resolution. We also document every step of the process to maintain a transparent record. Post-repair, we maintain ongoing performance monitoring to ensure the issue does not recur and to identify any broader patterns that might indicate systemic concerns. This closed-loop approach, from design and performance benchmarking through to post-handover monitoring and defect resolution, ensures our solar PV systems operate reliably and efficiently for the long term, delivering on both energy and carbon reduction promises. Our cost per year.",
      annualOutputkWh: "1534004",
      annualConsumptionkWh: "763481",
      selfSufficiencyPercent: "0",
      annualExportkWh: "770524",
      panelWarrantyYears: "25",
      inverterWarrantyYears: "10",
      workmanshipWarrantyYears: "7",
      systemLifetimeYears: "25",
    },
    additionalNotes: "",
    keyDifferentiator: "",
    documents: [
      { name: "Carraldo-specs.pdf", url: "#" },
      { name: "Carraldo-financials.xlsx", url: "#" },
    ],
  },
  {
    id: "14",
    name: "Alterum Partners",
    logo: "/site elements/solar pv logos/Alterum Test Supplier.png",
    price: 1236392.2,
    fields: {
      deliveryTime: "14",
      maintenanceTerm: "5",
      ppa: "Yes",
      leadTimeWeeks: "4",
      installationDays: "60",
      commissioningDays: "14",
      capexAvailable: "TRUE",
      capexUpfrontGBP: "1236392.2",
      capexAnnualGBP: "19727",
      capexMinTermYears: "5",
      hpAvailable: "FALSE",
      hpUpfrontGBP: "",
      hpAnnualGBP: "",
      hpTermYears: "",
      ppaAvailable: "TRUE",
      ppaUpfrontGBP: "0",
      ppaAnnualGBP: "0",
      ppaTermYears: "25",
      maintenancePriceGBP: "19727",
      oMApproach: "This cost covers monitoring and remote management to ensure the ongoing reliability and performance of the installed systems. It includes annual Remote Health Checks, Remote Software Diagnostics, and the implementation of Software and Firmware Upgrades as needed. The service also provides access to chargeable repair services, full warranty management, and 365-day system alert monitoring. In the event of a fault, Remote Fault Investigation is included to diagnose issues promptly. The package also covers the provision and maintenance of the data connection required for remote services. Please note that this price excludes any access equipment, which will be charged separately if required for on-site interventions.",
      annualOutputkWh: "1405865",
      annualConsumptionkWh: "1126098",
      selfSufficiencyPercent: "0",
      annualExportkWh: "279767",
      panelWarrantyYears: "25",
      inverterWarrantyYears: "10",
      workmanshipWarrantyYears: "2",
      systemLifetimeYears: "35",
    },
    additionalNotes: "",
    keyDifferentiator: "",
    documents: [
      { name: "Alterum-offer.pdf", url: "#" },
      { name: "Alterum-timeline.xlsx", url: "#" },
    ],
  },
  {
    id: "15",
    name: "Northern Generators",
    logo: "/site elements/solar pv logos/Northern Generators.png",
    price: 1340884,
    fields: {
      deliveryTime: "40",
      maintenanceTerm: "1",
      ppa: "No",
      leadTimeWeeks: "10",
      installationDays: "120",
      commissioningDays: "20",
      capexAvailable: "TRUE",
      capexUpfrontGBP: "1340884",
      capexAnnualGBP: "20196",
      capexMinTermYears: "1",
      hpAvailable: "FALSE",
      hpUpfrontGBP: "",
      hpAnnualGBP: "",
      hpTermYears: "",
      ppaAvailable: "FALSE",
      ppaUpfrontGBP: "",
      ppaAnnualGBP: "",
      ppaTermYears: "",
      maintenancePriceGBP: "20196",
      oMApproach: "While there are no scheduled visits, it is assumed that up to two site attendances may be required during this period. The amount covers labour, with all replacement products expected to be covered under warranty.",
      annualOutputkWh: "1115340",
      annualConsumptionkWh: "641450",
      selfSufficiencyPercent: "0",
      annualExportkWh: "471040",
      panelWarrantyYears: "25",
      inverterWarrantyYears: "12",
      workmanshipWarrantyYears: "1",
      systemLifetimeYears: "30",
    },
    additionalNotes: "",
    keyDifferentiator: "",
    documents: [
      { name: "Northern-technical-spec.pdf", url: "#" },
      { name: "Northern-costing.xlsx", url: "#" },
    ],
  },
  {
    id: "16",
    name: "APN Renewables",
    logo: "/site elements/solar pv logos/APN.png",
    price: 1116698.97,
    fields: {
      deliveryTime: "21",
      maintenanceTerm: "5",
      ppa: "Yes",
      leadTimeWeeks: "5",
      installationDays: "84",
      commissioningDays: "14",
      capexAvailable: "TRUE",
      capexUpfrontGBP: "1116698.97",
      capexAnnualGBP: "16000",
      capexMinTermYears: "5",
      hpAvailable: "TRUE",
      hpUpfrontGBP: "",
      hpAnnualGBP: "",
      hpTermYears: "",
      ppaAvailable: "FALSE",
      ppaUpfrontGBP: "",
      ppaAnnualGBP: "",
      ppaTermYears: "",
      maintenancePriceGBP: "16000",
      oMApproach: "Undertake an annual maintenance package excluding cleaning. It does include monthly monitoring and reporting on system performance.",
      annualOutputkWh: "1263170",
      annualConsumptionkWh: "780008",
      selfSufficiencyPercent: "0",
      annualExportkWh: "483162",
      panelWarrantyYears: "25",
      inverterWarrantyYears: "12",
      workmanshipWarrantyYears: "2",
      systemLifetimeYears: "40",
    },
    additionalNotes: "",
    keyDifferentiator: "",
    documents: [
      { name: "APN-proposal.pdf", url: "#" },
      { name: "APN-schedule.xlsx", url: "#" },
    ],
  },
  {
    id: "17",
    name: "Energis GmbH",
    logo: "/site elements/solar pv logos/Energis.png",
    price: 1659339,
    fields: {
      deliveryTime: "21",
      maintenanceTerm: "2",
      ppa: "No",
      leadTimeWeeks: "3",
      installationDays: "60",
      commissioningDays: "14",
      capexAvailable: "TRUE",
      capexUpfrontGBP: "1659339",
      capexAnnualGBP: "19500",
      capexMinTermYears: "2",
      hpAvailable: "FALSE",
      hpUpfrontGBP: "",
      hpAnnualGBP: "",
      hpTermYears: "",
      ppaAvailable: "FALSE",
      ppaUpfrontGBP: "",
      ppaAnnualGBP: "",
      ppaTermYears: "",
      maintenancePriceGBP: "19500",
      oMApproach: "Daily monitoring, full annual inspection. Spot cleaning of modules, fault finding",
      annualOutputkWh: "1281051",
      annualConsumptionkWh: "3840000",
      selfSufficiencyPercent: "0",
      annualExportkWh: "0",
      panelWarrantyYears: "12",
      inverterWarrantyYears: "5",
      workmanshipWarrantyYears: "2",
      systemLifetimeYears: "25",
    },
    additionalNotes: "",
    keyDifferentiator: "",
    documents: [
      { name: "Energis-specs.pdf", url: "#" },
      { name: "Energis-financials.xlsx", url: "#" },
    ],
  },
]

const solarCategories: Category[] = [
  {
    name: "Overview",
    expanded: true,
    fields: [
      { label: "Lead time (weeks)", key: "leadTimeWeeks" },
      { label: "Installation (days)", key: "installationDays" },
      { label: "Delivery (days)", key: "deliveryTime" },
      { label: "Commissioning (days)", key: "commissioningDays" },
    ],
  },
  {
    name: "Capex",
    expanded: true,
    fields: [
      { label: "CapEx available", key: "capexAvailable" },
      { label: "CapEx upfront (GBP)", key: "capexUpfrontGBP" },
      { label: "CapEx annual (GBP)", key: "capexAnnualGBP" },
      { label: "CapEx min term (years)", key: "capexMinTermYears" },
    ],
  },
  {
    name: "Hire Purchase",
    expanded: true,
    fields: [
      { label: "HP available", key: "hpAvailable" },
      { label: "HP upfront (GBP)", key: "hpUpfrontGBP" },
      { label: "HP annual (GBP)", key: "hpAnnualGBP" },
      { label: "HP term (years)", key: "hpTermYears" },
    ],
  },
  {
    name: "PPA",
    expanded: true,
    fields: [
      { label: "PPA available", key: "ppaAvailable" },
      { label: "PPA upfront (GBP)", key: "ppaUpfrontGBP" },
      { label: "PPA annual (GBP)", key: "ppaAnnualGBP" },
      { label: "PPA term (years)", key: "ppaTermYears" },
    ],
  },
  {
    name: "Maintenance",
    expanded: true,
    fields: [
      { label: "Maintenance term (years)", key: "maintenanceTerm" },
      { label: "Maintenance price (GBP)", key: "maintenancePriceGBP" },
      { label: "O&M approach", key: "oMApproach" },
    ],
  },
  {
    name: "Technical",
    expanded: true,
    fields: [
      { label: "Annual output (kWh)", key: "annualOutputkWh" },
      { label: "Annual consumption (kWh)", key: "annualConsumptionkWh" },
      { label: "Self-sufficiency (%)", key: "selfSufficiencyPercent" },
      { label: "Annual export (kWh)", key: "annualExportkWh" },
      { label: "Panel warranty (years)", key: "panelWarrantyYears" },
      { label: "Inverter warranty (years)", key: "inverterWarrantyYears" },
      { label: "Workmanship warranty (years)", key: "workmanshipWarrantyYears" },
      { label: "System lifetime (years)", key: "systemLifetimeYears" },
    ],
  },
]

const solarFieldExplanations: Record<string, string> = {
  deliveryTime: "Number of days until project delivery.",
  maintenanceTerm: "Length of maintenance contract in years.",
  ppa: "Whether a Power Purchase Agreement is included.",
  leadTimeWeeks: "Number of weeks required before installation can begin.",
  installationDays: "Number of days required for installation work.",
  commissioningDays: "Number of days required for commissioning and testing.",
  capexAvailable: "Whether capital expenditure financing is available.",
  capexUpfrontGBP: "Upfront capital expenditure amount in GBP.",
  capexAnnualGBP: "Annual capital expenditure payment in GBP.",
  capexMinTermYears: "Minimum term for capital expenditure agreement in years.",
  hpAvailable: "Whether Hire Purchase financing is available.",
  hpUpfrontGBP: "Upfront Hire Purchase payment in GBP.",
  hpAnnualGBP: "Annual Hire Purchase payment in GBP.",
  hpTermYears: "Hire Purchase agreement term in years.",
  ppaAvailable: "Whether Power Purchase Agreement is available.",
  ppaUpfrontGBP: "Upfront Power Purchase Agreement payment in GBP.",
  ppaAnnualGBP: "Annual Power Purchase Agreement payment in GBP.",
  ppaTermYears: "Power Purchase Agreement term in years.",
  maintenancePriceGBP: "Annual maintenance price in GBP.",
  oMApproach: "Operations & Maintenance approach and services description.",
  annualOutputkWh: "Expected annual energy output in kilowatt-hours.",
  annualConsumptionkWh: "Expected annual energy consumption in kilowatt-hours.",
  selfSufficiencyPercent: "Percentage of energy needs met by the system.",
  annualExportkWh: "Expected annual energy export to grid in kilowatt-hours.",
  panelWarrantyYears: "Warranty period for solar panels in years.",
  inverterWarrantyYears: "Warranty period for inverters in years.",
  workmanshipWarrantyYears: "Warranty period for workmanship in years.",
  systemLifetimeYears: "Expected system lifetime in years.",
}

const hvacSuppliers: Supplier[] = [
  {
    id: "21",
    name: "Nordic ClimateWorks",
    logo: "/site elements/gogreen.svg",
    price: 610000,
    fields: {
      hvacScope: "Replace 6 AHUs + duct rebalancing",
      heatSource: "Air-to-water heat pumps",
      ventilationStrategy: "Demand-controlled w/ CO₂ sensors",
      controlsStack: "Siemens Desigo upgrade",
      installWindow: "18 weeks",
      downtimePlan: "Weekend changeovers only",
      bmsIntegration: "Native BACnet/IP",
      commissioning: "Retro-commission + M&V",
      warranties: "2y labour / 5y equipment",
      servicePlan: "Gold SLA (same-day)",
    },
    additionalNotes: "Includes temporary chillers for switchover.",
    keyDifferentiator: "Deep Desigo expertise and low downtime.",
    documents: [
      { name: "Nordic-scope.pdf", url: "#" },
      { name: "Nordic-programme.mpp", url: "#" },
    ],
  },
  {
    id: "22",
    name: "Metro HVAC Alliance",
    logo: "/site elements/beba.svg",
    price: 575000,
    fields: {
      hvacScope: "Refurbish AHUs, new VFDs",
      heatSource: "Hybrid heat pump + gas backup",
      ventilationStrategy: "Constant volume + VAV boxes",
      controlsStack: "Honeywell Niagara",
      installWindow: "16 weeks",
      downtimePlan: "Night shift works",
      bmsIntegration: "BACnet gateway only",
      commissioning: "Standard start-up",
      warranties: "1y labour / 3y equipment",
      servicePlan: "Bronze SLA",
    },
    additionalNotes: "Client to supply scaffolding and permits.",
    keyDifferentiator: "Balanced CapEx with staged delivery.",
    documents: [
      { name: "Metro-offer.pdf", url: "#" },
      { name: "Metro-schedule.xlsx", url: "#" },
    ],
  },
  {
    id: "23",
    name: "ClimaSphere GmbH",
    logo: "/site elements/hysopt.svg",
    price: 640000,
    fields: {
      hvacScope: "New AHUs, duct/electrical",
      heatSource: "Water-to-water heat pumps",
      ventilationStrategy: "Displacement ventilation",
      controlsStack: "Schneider EcoStruxure",
      installWindow: "20 weeks",
      downtimePlan: "Phased block shut-downs",
      bmsIntegration: "Full graphics refresh",
      commissioning: "Level 5 commissioning",
      warranties: "3y labour / 5y equipment",
      servicePlan: "Platinum 4-hour response",
    },
    additionalNotes: "Includes acoustic upgrades and insulation.",
    keyDifferentiator: "Best-in-class commissioning protocol.",
    documents: [
      { name: "ClimaSphere-spec.pdf", url: "#" },
      { name: "ClimaSphere-finance.xlsx", url: "#" },
    ],
  },
  {
    id: "24",
    name: "Ventum Solutions",
    logo: "/site elements/lowcarbon.svg",
    price: 590000,
    fields: {
      hvacScope: "AHU coil replacement + controls",
      heatSource: "Existing chillers + new boilers",
      ventilationStrategy: "Like-for-like constant volume",
      controlsStack: "Existing BMS overlays",
      installWindow: "15 weeks",
      downtimePlan: "Client managed",
      bmsIntegration: "Limited trending",
      commissioning: "Factory testing only",
      warranties: "1y equipment",
      servicePlan: "Reactive call-out",
    },
    additionalNotes: "Scope excludes balancing.",
    keyDifferentiator: "Lowest cost, limited scope.",
    documents: [
      { name: "Ventum-offer.pdf", url: "#" },
    ],
  },
]

const hvacCategories: Category[] = [
  {
    name: "Mechanical Scope",
    expanded: true,
    fields: [
      { label: "Scope summary", key: "hvacScope" },
      { label: "Heat/cool source", key: "heatSource" },
      { label: "Ventilation strategy", key: "ventilationStrategy" },
    ],
  },
  {
    name: "Controls & Delivery",
    expanded: true,
    fields: [
      { label: "Controls / BMS stack", key: "controlsStack" },
      { label: "Install window", key: "installWindow" },
      { label: "Downtime plan", key: "downtimePlan" },
      { label: "BMS integration", key: "bmsIntegration" },
      { label: "Commissioning approach", key: "commissioning" },
    ],
  },
  {
    name: "Support",
    expanded: true,
    fields: [
      { label: "Warranty coverage", key: "warranties" },
      { label: "Service plan", key: "servicePlan" },
    ],
  },
]

const hvacFieldExplanations: Record<string, string> = {
  hvacScope: "Headline summary of mechanical works.",
  heatSource: "Primary equipment providing heating/cooling.",
  ventilationStrategy: "Air distribution and control strategy.",
  controlsStack: "Controls platform and integrations.",
  installWindow: "Duration to execute site works.",
  downtimePlan: "How the contractor mitigates occupant disruption.",
  bmsIntegration: "Depth of integration with existing BMS.",
  commissioning: "Commissioning and validation approach.",
  warranties: "Labour and equipment warranty coverage.",
  servicePlan: "Post-handover service levels.",
}

export const tenderConfigs: Record<TenderScenario, TenderConfig> = {
  "heat-pump": {
    slug: "heat-pump",
    title: "LED - Waldemarstraße",
    description: "LED retrofit and controls tender for an occupied office building.",
    location: "Waldemarstraße 57, Berlin, 10997, DE",
    avatar: "/site elements/Avatar.svg",
    tags: ["OCCUPIED", "OFFICE"],
    overview: {
      invited: 10,
      submitted: 4,
      responseRate: 40,
      details: [
        "1 didn't have capacity",
        "2 didn't respond",
        "3 excluded (incomplete pricing)",
        "4 submitted",
      ],
      closedDate: "15 Oct 2025",
      duration: "14 days",
    },
    suppliers: heatPumpSuppliers,
    categories: heatPumpCategories,
    fieldExplanations: heatPumpFieldExplanations,
  },
  "solar-pv": {
    slug: "solar-pv",
    title: "Solar PV - Northampton Corn Exchange",
    description: "1 MW+ rooftop PV tender for a commercial heritage site.",
    location: "4 Market Square, Northampton, NN1 1DE, UK",
    avatar: "/site elements/Avatar.svg",
    tags: ["COMMERCIAL", "+1MW SOLAR"],
    overview: {
      invited: 20,
      submitted: 7,
      responseRate: 35,
      details: [
        "5 didn't respond",
        "4 missed the deadline",
        "3 didn't work on projects of this size",
        "1 excluded (incomplete pricing)",
        "7 submitted",
      ],
      closedDate: "28 Oct 2025",
      duration: "21 days",
    },
    suppliers: solarSuppliers,
    categories: solarCategories,
    fieldExplanations: solarFieldExplanations,
  },
  hvac: {
    slug: "hvac",
    title: "ASHP - Erfstraße 15-20",
    description: "Air-source heat pump upgrade for an occupied hotel asset.",
    location: "Erfstraße 15-20, Köln, 50672, DE",
    avatar: "/site elements/Avatar.svg",
    tags: ["HOTEL", "OCCUPIED"],
    overview: {
      invited: 10,
      submitted: 5,
      responseRate: 50,
      details: [
        "3 didn't respond",
        "3 didn't work on projects of this size",
        "1 excluded (incomplete pricing)",
        "4 submitted",
      ],
      closedDate: "05 Nov 2025",
      duration: "18 days",
    },
    suppliers: hvacSuppliers,
    categories: hvacCategories,
    fieldExplanations: hvacFieldExplanations,
  },
}

export const tenderList = Object.values(tenderConfigs)

export function getTenderConfig(slug: string): TenderConfig | undefined {
  return tenderConfigs[slug as TenderScenario]
}
