import type { Category, Supplier, TenderConfig, TenderScenario } from "@/types/tender"

const heatPumpSuppliers: Supplier[] = [
  {
    id: "1",
    name: "Energis GmbH",
    logo: "/site elements/solar pv logos/Energis.png",
    price: 24337.59,
    fields: {
      totalLamps: "80",
      totalCostEUR: "24337.59",
      maxCostEUR: "24337.59",
      leadTimeWeeks: "1",
      installationDays: "5",
      lampWarrantyYears: "5",
      costPerLampEUR: "304.22",
      materialsEUR: "12793.29",
      labourEUR: "9343.4",
      maintenanceEUR: "—",
      materialsPercent: "52.6",
      labourPercent: "38.4",
      deliveryTime: "5",
      commissioningDays: "—",
      annualEnergykWh: "13632",
      energyDemandW: "3.82",
      runningHoursPerYear: "6500",
      workmanshipWarrantyYears: "1",
      solutionLifespanYears: "25",
      componentWarrantyYears: "3",
    },
    additionalNotes: "",
    keyDifferentiator: "Very competitive pricing and comprehensive coverage. They offer the longest running hours at 6,500 per year and achieve the longest solution lifespan at 25 years.",
    documents: [
      { name: "Technical spec.pdf", url: "#" },
      { name: "Pricing breakdown.xlsx", url: "#" },
    ],
  },
  {
    id: "2",
    name: "Carraldo Energy",
    logo: "/site elements/solar pv logos/Carraldo Test Supplier.png",
    price: 20777.39,
    fields: {
      totalLamps: "140",
      totalCostEUR: "20777.39",
      maxCostEUR: "20777.39",
      leadTimeWeeks: "6",
      installationDays: "—",
      lampWarrantyYears: "0",
      costPerLampEUR: "148.41",
      materialsEUR: "—",
      labourEUR: "—",
      maintenanceEUR: "—",
      materialsPercent: "—",
      labourPercent: "—",
      deliveryTime: "42",
      commissioningDays: "—",
      annualEnergykWh: "0",
      energyDemandW: "11100",
      runningHoursPerYear: "0",
      workmanshipWarrantyYears: "0",
      solutionLifespanYears: "0",
      componentWarrantyYears: "0",
    },
    additionalNotes: "",
    keyDifferentiator: "Provides the lowest total cost; however, their bid contains significant data gaps that requires further clarifications.",
    documents: [
      { name: "Technical spec.pdf", url: "#" },
      { name: "Pricing breakdown.xlsx", url: "#" },
    ],
  },
  {
    id: "3",
    name: "HHT Group",
    logo: "/site elements/solar pv logos/HHT Group.png",
    price: 12316,
    fields: {
      totalLamps: "40",
      totalCostEUR: "12316",
      maxCostEUR: "12316",
      leadTimeWeeks: "6",
      installationDays: "—",
      lampWarrantyYears: "5",
      costPerLampEUR: "307.9",
      materialsEUR: "—",
      labourEUR: "—",
      maintenanceEUR: "—",
      materialsPercent: "—",
      labourPercent: "—",
      deliveryTime: "42",
      commissioningDays: "—",
      annualEnergykWh: "15768",
      energyDemandW: "3600",
      runningHoursPerYear: "4380",
      workmanshipWarrantyYears: "5",
      solutionLifespanYears: "23",
      componentWarrantyYears: "5",
    },
    additionalNotes: "",
    keyDifferentiator: "Offers matching 5-year warranties for both lamps and workmanship (the only supplier with equal warranty periods), demonstrating confidence in both product and installation quality.",
    documents: [
      { name: "Technical spec.pdf", url: "#" },
      { name: "Pricing breakdown.xlsx", url: "#" },
    ],
  },
  {
    id: "4",
    name: "Alterum Partners",
    logo: "/site elements/solar pv logos/Alterum Test Supplier.png",
    price: 70670,
    fields: {
      totalLamps: "40",
      totalCostEUR: "70670",
      maxCostEUR: "70670",
      leadTimeWeeks: "2",
      installationDays: "14",
      lampWarrantyYears: "5",
      costPerLampEUR: "1766.75",
      materialsEUR: "42000",
      labourEUR: "19040",
      maintenanceEUR: "1150",
      materialsPercent: "59.4",
      labourPercent: "26.9",
      deliveryTime: "28",
      commissioningDays: "7",
      annualEnergykWh: "17640",
      energyDemandW: "4200",
      runningHoursPerYear: "4200",
      workmanshipWarrantyYears: "2",
      solutionLifespanYears: "24",
      componentWarrantyYears: "5",
    },
    additionalNotes: "",
    keyDifferentiator: "Has by far the highest cost, but includes detailed cost breakdowns with €1,150 annual maintenance explicitly itemized.",
    documents: [
      { name: "Technical spec.pdf", url: "#" },
      { name: "Pricing breakdown.xlsx", url: "#" },
    ],
  },
]

const heatPumpCategories: Category[] = [
  {
    name: "Overview",
    expanded: true,
    fields: [
      { label: "Total Lamps", key: "totalLamps", tooltip: "Total number of lamps in the project." },
      { label: "Total Cost", key: "totalCostEUR", tooltip: "Total project cost in Euros." },
      { label: "Max Cost", key: "maxCostEUR", tooltip: "Maximum project cost in Euros." },
      { label: "Lead Time", key: "leadTimeWeeks", tooltip: "Number of weeks required before installation can begin." },
      { label: "Installation", key: "installationDays", tooltip: "Number of days required for installation work." },
      { label: "Lamp Warranty", key: "lampWarrantyYears", tooltip: "Warranty period for lamps in years." },
      { label: "Cost per Lamp", key: "costPerLampEUR", tooltip: "Cost per individual lamp in Euros." },
    ],
  },
  {
    name: "Cost Breakdown",
    expanded: true,
    fields: [
      { label: "Materials", key: "materialsEUR", tooltip: "Cost of materials in Euros." },
      { label: "Labour", key: "labourEUR", tooltip: "Cost of labour in Euros." },
      { label: "Maintenance", key: "maintenanceEUR", tooltip: "Cost of maintenance in Euros." },
      { label: "Materials", key: "materialsPercent", tooltip: "Percentage of total cost attributed to materials." },
      { label: "Labour", key: "labourPercent", tooltip: "Percentage of total cost attributed to labour." },
    ],
  },
  {
    name: "Timelines",
    expanded: true,
    fields: [
      { label: "Lead Time", key: "leadTimeWeeks", tooltip: "Number of weeks required before installation can begin." },
      { label: "Delivery", key: "deliveryTime", tooltip: "Number of days until delivery." },
      { label: "Installation", key: "installationDays", tooltip: "Number of days required for installation work." },
      { label: "Commissioning", key: "commissioningDays", tooltip: "Number of days required for commissioning and testing." },
    ],
  },
  {
    name: "Energy",
    expanded: true,
    fields: [
      { label: "Total Lamps", key: "totalLamps", tooltip: "Total number of lamps in the project." },
      { label: "Annual Energy", key: "annualEnergykWh", tooltip: "Expected annual energy consumption in kilowatt-hours." },
      { label: "Energy Demand", key: "energyDemandW", tooltip: "Energy demand in watts." },
      { label: "Running Hours per Year", key: "runningHoursPerYear", tooltip: "Number of hours the system runs per year." },
    ],
  },
  {
    name: "Warranties",
    expanded: true,
    fields: [
      { label: "Lamp Warranty", key: "lampWarrantyYears", tooltip: "Warranty period for lamps in years." },
      { label: "Workmanship Warranty", key: "workmanshipWarrantyYears", tooltip: "Warranty period for workmanship in years." },
      { label: "Solution Lifespan", key: "solutionLifespanYears", tooltip: "Expected operational lifetime of the solution in years." },
      { label: "Component Warranty", key: "componentWarrantyYears", tooltip: "Warranty period for components in years." },
    ],
  },
]

const heatPumpFieldExplanations: Record<string, string> = {
  totalLamps: "Total number of lamps in the project.",
  totalCostEUR: "Total project cost in Euros.",
  maxCostEUR: "Maximum project cost in Euros.",
  leadTimeWeeks: "Number of weeks required before installation can begin.",
  installationDays: "Number of days required for installation work.",
  lampWarrantyYears: "Warranty period for lamps in years.",
  costPerLampEUR: "Cost per individual lamp in Euros.",
  materialsEUR: "Cost of materials in Euros.",
  labourEUR: "Cost of labour in Euros.",
  maintenanceEUR: "Cost of maintenance in Euros.",
  materialsPercent: "Percentage of total cost attributed to materials.",
  labourPercent: "Percentage of total cost attributed to labour.",
  deliveryTime: "Number of days until delivery.",
  commissioningDays: "Number of days required for commissioning and testing.",
  annualEnergykWh: "Expected annual energy consumption in kilowatt-hours.",
  energyDemandW: "Energy demand in watts.",
  runningHoursPerYear: "Number of hours the system runs per year.",
  workmanshipWarrantyYears: "Warranty period for workmanship in years.",
  solutionLifespanYears: "Expected operational lifetime of the solution in years.",
  componentWarrantyYears: "Warranty period for components in years.",
}

const solarSuppliers: Supplier[] = [
  {
    id: "11",
    name: "HHT Group",
    logo: "/site elements/solar pv logos/HHT Group.png",
    price: 1417886,
    fields: {
      deliveryTime: "7",
      maintenanceTerm: "5",
      ppa: "Yes",
      leadTimeWeeks: "3",
      installationDays: "80",
      commissioningDays: "7",
      capexAvailable: "TRUE",
      capexUpfrontGBP: "1417886",
      capexAnnualGBP: "19728",
      capexMinTermYears: "5",
      hpAvailable: "TRUE",
      hpUpfrontGBP: "",
      hpAnnualGBP: "",
      hpTermYears: "",
      ppaAvailable: "TRUE",
      ppaUpfrontGBP: "0",
      ppaAnnualGBP: "0",
      ppaTermYears: "25",
      maintenancePriceGBP: "19729",
      oMApproach: "Our O&M is free of charge and included with the PPA. An additional cost is required for capex purchases. We have stated an initial timeframe of 5 years for paid O&M but this can be as long as the client wants it to be. PPA O&M is as long as the PPA agreement. Operations & Maintenance Services As both the owner and operator of the solar projects they fund, HHT Group provides: Annual Maintenance Services: Regular inspections and maintenance to ensure optimal performance of solar installations. Performance Monitoring: Utilization of advanced technologies, such as SolarEdge's DC-optimized systems, to monitor system performance in real-time, enabling rapid fault detection and maintenance. Long-Term Support: Ongoing support throughout the project's lifespan, including addressing concerns and optimizing system performance. Remote monitoring: 24/7 monitoring of the system performance via its online monitoring platform, allowing for instant identification of issues as they arise and a proactive approach to maintenance Priority support: in the event of any issues, priority access to our site team resources to resolve sooner and minimise downtime.",
      annualOutputkWh: "1340277",
      annualConsumptionkWh: "634449",
      selfSufficiencyPercent: "0",
      annualExportkWh: "705828",
      panelWarrantyYears: "25",
      inverterWarrantyYears: "10",
      workmanshipWarrantyYears: "1",
      systemLifetimeYears: "25",
    },
    supplierRelevance: {
      generalScore: 4.5,
      assetType: 5,
      stakeholderManagement: 4,
      assetSize: 5,
      location: 4,
    },
    categoryScores: {
      financial: 4.2,
      relevance: 4.5,
      speed: 4.0,
      technical: 4.3,
    },
    additionalNotes: "",
    keyDifferentiator: "Offers a comprehensive 25-year PPA option with free O&M included throughout, making it the most flexible financing option with no upfront costs.",
    documents: [
      { name: "HHT-technical-spec.pdf", url: "#" },
      { name: "HHT-costing.xlsx", url: "#" },
    ],
  },
  {
    id: "12",
    name: "SONNE Power",
    logo: "/site elements/solar pv logos/Sonne Test Supplier.png",
    price: 1301582.81,
    fields: {
      deliveryTime: "10",
      maintenanceTerm: "5",
      ppa: "No",
      leadTimeWeeks: "3",
      installationDays: "84",
      commissioningDays: "5",
      capexAvailable: "TRUE",
      capexUpfrontGBP: "1301582.81",
      capexAnnualGBP: "2750",
      capexMinTermYears: "5",
      hpAvailable: "FALSE",
      hpUpfrontGBP: "",
      hpAnnualGBP: "",
      hpTermYears: "",
      ppaAvailable: "FALSE",
      ppaUpfrontGBP: "",
      ppaAnnualGBP: "",
      ppaTermYears: "",
      maintenancePriceGBP: "2750",
      oMApproach: "Annual audit: a physical check of the full health of the system across all components. This includes inspection and testing of the electrical components to ensure system output is in line with expectations, inspection of the array and mounting to check for damage and ensure structural integrity, and a full thermography inspection of the system to identify any electrical issues before they arise. Services Included - Annual servicing: Catch any warning signs and prevent problems from developing. 24/7 remote system monitoring: Our office team monitor the performance of your system daily, reducing potential downtime. Technical: Telephone support and troubleshooting to resolve minor problems or errors. Quarterly and annual performance report: Provides an overview of your energy portfolio and any advisory actions. Maintenance and repairs: In case of a fault, our engineers will get you back up and running.",
      annualOutputkWh: "1470000",
      annualConsumptionkWh: "718000",
      selfSufficiencyPercent: "0",
      annualExportkWh: "752000",
      panelWarrantyYears: "25",
      inverterWarrantyYears: "20",
      workmanshipWarrantyYears: "2",
      systemLifetimeYears: "25",
    },
    supplierRelevance: {
      generalScore: 4.0,
      assetType: 4,
      stakeholderManagement: 4,
      assetSize: 4,
      location: 4,
    },
    categoryScores: {
      financial: 4.0,
      relevance: 4.0,
      speed: 4.5,
      technical: 4.5,
    },
    additionalNotes: "",
    keyDifferentiator: "Provides the longest inverter warranty at 20 years (double most competitors), significantly reducing long-term replacement costs and risk.",
    documents: [
      { name: "SONNE-proposal.pdf", url: "#" },
      { name: "SONNE-schedule.xlsx", url: "#" },
    ],
  },
  {
    id: "13",
    name: "Carraldo Energy",
    logo: "/site elements/solar pv logos/Carraldo Test Supplier.png",
    price: 1151973,
    fields: {
      deliveryTime: "14",
      maintenanceTerm: "10",
      ppa: "No",
      leadTimeWeeks: "4",
      installationDays: "60",
      commissioningDays: "10",
      capexAvailable: "TRUE",
      capexUpfrontGBP: "1151973",
      capexAnnualGBP: "15000",
      capexMinTermYears: "10",
      hpAvailable: "FALSE",
      hpUpfrontGBP: "",
      hpAnnualGBP: "",
      hpTermYears: "",
      ppaAvailable: "FALSE",
      ppaUpfrontGBP: "",
      ppaAnnualGBP: "",
      ppaTermYears: "",
      maintenancePriceGBP: "15000",
      oMApproach: "Cleaning: If required, Our specialist solar panel cleaning service will be provided to improve the efficiency of the system. To ensure the long-term success and reliability of our solar PV systems, we implement a comprehensive approach to performance monitoring and post-installation support. This begins immediately after the system is commissioned, when we activate remote monitoring tools that continuously track the system's output. These tools allow us to compare real-time performance data against the expected generation levels defined in the design phase. If performance drops below guaranteed thresholds, alerts are triggered so issues can be promptly investigated and resolved. Our support doesn't end at handover. We schedule follow-up calls or site visits to verify the system's performance, answer any client questions, and address potential concerns. If a defect or performance issue arises, we have structured processes in place for identifying, documenting, and resolving faults. Clients are given straightforward procedures to report any issues, which are logged in our service management system. From there, a qualified service engineer is deployed to diagnose the problem using appropriate diagnostic tools. Once a defect is identified, a clear rectification plan is created and shared with the client. Repairs are executed by certified technicians, and each fix is followed by testing to verify successful resolution. We also document every step of the process to maintain a transparent record. Post-repair, we maintain ongoing performance monitoring to ensure the issue does not recur and to identify any broader patterns that might indicate systemic concerns. This closed-loop approach, from design and performance benchmarking through to post-handover monitoring and defect resolution, ensures our solar PV systems operate reliably and efficiently for the long term, delivering on both energy and carbon reduction promises. Our cost per year.",
      annualOutputkWh: "1534004",
      annualConsumptionkWh: "763481",
      selfSufficiencyPercent: "0",
      annualExportkWh: "770524",
      panelWarrantyYears: "25",
      inverterWarrantyYears: "10",
      workmanshipWarrantyYears: "7",
      systemLifetimeYears: "25",
    },
    supplierRelevance: {
      generalScore: 4.2,
      assetType: 4,
      stakeholderManagement: 5,
      assetSize: 4,
      location: 4,
    },
    categoryScores: {
      financial: 4.5,
      relevance: 4.2,
      speed: 3.5,
      technical: 4.7,
    },
    additionalNotes: "",
    keyDifferentiator: "Offers the longest workmanship warranty at 7 years along with included specialist solar panel cleaning services, providing exceptional installation quality assurance.",
    documents: [
      { name: "Carraldo-specs.pdf", url: "#" },
      { name: "Carraldo-financials.xlsx", url: "#" },
    ],
  },
  {
    id: "14",
    name: "Alterum Partners",
    logo: "/site elements/solar pv logos/Alterum Test Supplier.png",
    price: 1236392.2,
    fields: {
      deliveryTime: "14",
      maintenanceTerm: "5",
      ppa: "Yes",
      leadTimeWeeks: "4",
      installationDays: "60",
      commissioningDays: "14",
      capexAvailable: "TRUE",
      capexUpfrontGBP: "1236392.2",
      capexAnnualGBP: "19727",
      capexMinTermYears: "5",
      hpAvailable: "FALSE",
      hpUpfrontGBP: "",
      hpAnnualGBP: "",
      hpTermYears: "",
      ppaAvailable: "TRUE",
      ppaUpfrontGBP: "0",
      ppaAnnualGBP: "0",
      ppaTermYears: "25",
      maintenancePriceGBP: "19727",
      oMApproach: "This cost covers monitoring and remote management to ensure the ongoing reliability and performance of the installed systems. It includes annual Remote Health Checks, Remote Software Diagnostics, and the implementation of Software and Firmware Upgrades as needed. The service also provides access to chargeable repair services, full warranty management, and 365-day system alert monitoring. In the event of a fault, Remote Fault Investigation is included to diagnose issues promptly. The package also covers the provision and maintenance of the data connection required for remote services. Please note that this price excludes any access equipment, which will be charged separately if required for on-site interventions.",
      annualOutputkWh: "1405865",
      annualConsumptionkWh: "1126098",
      selfSufficiencyPercent: "0",
      annualExportkWh: "279767",
      panelWarrantyYears: "25",
      inverterWarrantyYears: "10",
      workmanshipWarrantyYears: "2",
      systemLifetimeYears: "35",
    },
    supplierRelevance: {
      generalScore: 4.3,
      assetType: 4,
      stakeholderManagement: 4,
      assetSize: 5,
      location: 4,
    },
    categoryScores: {
      financial: 4.1,
      relevance: 4.3,
      speed: 3.8,
      technical: 4.4,
    },
    additionalNotes: "",
    keyDifferentiator: "Claims the longest system lifetime at 35 years and achieves the highest self-sufficiency rate at 80%, making it ideal for high energy users.",
    documents: [
      { name: "Alterum-offer.pdf", url: "#" },
      { name: "Alterum-timeline.xlsx", url: "#" },
    ],
  },
  {
    id: "15",
    name: "Northern Generators",
    logo: "/site elements/solar pv logos/Northern Generators.png",
    price: 1340884,
    fields: {
      deliveryTime: "40",
      maintenanceTerm: "1",
      ppa: "No",
      leadTimeWeeks: "10",
      installationDays: "120",
      commissioningDays: "20",
      capexAvailable: "TRUE",
      capexUpfrontGBP: "1340884",
      capexAnnualGBP: "20196",
      capexMinTermYears: "1",
      hpAvailable: "FALSE",
      hpUpfrontGBP: "",
      hpAnnualGBP: "",
      hpTermYears: "",
      ppaAvailable: "FALSE",
      ppaUpfrontGBP: "",
      ppaAnnualGBP: "",
      ppaTermYears: "",
      maintenancePriceGBP: "20196",
      oMApproach: "While there are no scheduled visits, it is assumed that up to two site attendances may be required during this period. The amount covers labour, with all replacement products expected to be covered under warranty.",
      annualOutputkWh: "1115340",
      annualConsumptionkWh: "641450",
      selfSufficiencyPercent: "0",
      annualExportkWh: "471040",
      panelWarrantyYears: "25",
      inverterWarrantyYears: "12",
      workmanshipWarrantyYears: "1",
      systemLifetimeYears: "30",
    },
    supplierRelevance: {
      generalScore: 3.5,
      assetType: 3,
      stakeholderManagement: 3,
      assetSize: 4,
      location: 4,
    },
    categoryScores: {
      financial: 3.8,
      relevance: 3.5,
      speed: 2.5,
      technical: 3.2,
    },
    additionalNotes: "",
    keyDifferentiator: "Has the longest lead time (10 weeks) and installation period (120 days) but offers the most affordable annual maintenance at £20,196 with comprehensive remote monitoring and software management.",
    documents: [
      { name: "Northern-technical-spec.pdf", url: "#" },
      { name: "Northern-costing.xlsx", url: "#" },
    ],
  },
  {
    id: "16",
    name: "APN Renewables",
    logo: "/site elements/solar pv logos/APN.png",
    price: 1116698.97,
    fields: {
      deliveryTime: "21",
      maintenanceTerm: "5",
      ppa: "Yes",
      leadTimeWeeks: "5",
      installationDays: "84",
      commissioningDays: "14",
      capexAvailable: "TRUE",
      capexUpfrontGBP: "1116698.97",
      capexAnnualGBP: "16000",
      capexMinTermYears: "5",
      hpAvailable: "TRUE",
      hpUpfrontGBP: "",
      hpAnnualGBP: "",
      hpTermYears: "",
      ppaAvailable: "FALSE",
      ppaUpfrontGBP: "",
      ppaAnnualGBP: "",
      ppaTermYears: "",
      maintenancePriceGBP: "16000",
      oMApproach: "Undertake an annual maintenance package excluding cleaning. It does include monthly monitoring and reporting on system performance.",
      annualOutputkWh: "1263170",
      annualConsumptionkWh: "780008",
      selfSufficiencyPercent: "0",
      annualExportkWh: "483162",
      panelWarrantyYears: "25",
      inverterWarrantyYears: "12",
      workmanshipWarrantyYears: "2",
      systemLifetimeYears: "40",
    },
    supplierRelevance: {
      generalScore: 4.1,
      assetType: 4,
      stakeholderManagement: 4,
      assetSize: 4,
      location: 4,
    },
    categoryScores: {
      financial: 4.3,
      relevance: 4.1,
      speed: 4.0,
      technical: 4.6,
    },
    additionalNotes: "",
    keyDifferentiator: "Features the longest total system lifetime at 40 years with a competitive price point of £1.12M, offering the best long-term value proposition.",
    documents: [
      { name: "APN-proposal.pdf", url: "#" },
      { name: "APN-schedule.xlsx", url: "#" },
    ],
  },
  {
    id: "17",
    name: "Energis GmbH",
    logo: "/site elements/solar pv logos/Energis.png",
    price: 1659339,
    fields: {
      deliveryTime: "21",
      maintenanceTerm: "2",
      ppa: "No",
      leadTimeWeeks: "3",
      installationDays: "60",
      commissioningDays: "14",
      capexAvailable: "TRUE",
      capexUpfrontGBP: "1659339",
      capexAnnualGBP: "19500",
      capexMinTermYears: "2",
      hpAvailable: "FALSE",
      hpUpfrontGBP: "",
      hpAnnualGBP: "",
      hpTermYears: "",
      ppaAvailable: "FALSE",
      ppaUpfrontGBP: "",
      ppaAnnualGBP: "",
      ppaTermYears: "",
      maintenancePriceGBP: "19500",
      oMApproach: "Daily monitoring, full annual inspection. Spot cleaning of modules, fault finding",
      annualOutputkWh: "1281051",
      annualConsumptionkWh: "3840000",
      selfSufficiencyPercent: "0",
      annualExportkWh: "0",
      panelWarrantyYears: "12",
      inverterWarrantyYears: "5",
      workmanshipWarrantyYears: "2",
      systemLifetimeYears: "25",
    },
    supplierRelevance: {
      generalScore: 3.8,
      assetType: 3,
      stakeholderManagement: 4,
      assetSize: 4,
      location: 4,
    },
    categoryScores: {
      financial: 3.2,
      relevance: 3.8,
      speed: 4.2,
      technical: 3.5,
    },
    additionalNotes: "",
    keyDifferentiator: "Shows an unusual profile with annual consumption of 3,840,000 kWh (far exceeding system output). They offer the shortest inverter warranty at just 5 years.",
    documents: [
      { name: "Energis-specs.pdf", url: "#" },
      { name: "Energis-financials.xlsx", url: "#" },
    ],
  },
]

const solarCategories: Category[] = [
  {
    name: "Supplier relevance",
    expanded: true,
    fields: [
      { 
        label: "Asset type", 
        key: "assetType", 
        isScore: true,
        tooltip: "Proven asset type experience:\n1. Retail centres\n2. Large numbers of visitors\n3. Common Parts\n4. High profile brand"
      },
      { 
        label: "Stakeholder management", 
        key: "stakeholderManagement", 
        isScore: true,
        tooltip: "Proven stakeholder experience:\n1. 60-200 Tenants\n2. Asset Managers"
      },
      { 
        label: "Asset size", 
        key: "assetSize", 
        isScore: true,
        tooltip: "Proven experience from delivering sizable solar systems to bigger commercial real estate assets with"
      },
      { 
        label: "Location", 
        key: "location", 
        isScore: true,
        tooltip: "Years & no. projects in UK commercial real estate"
      },
    ],
  },
  {
    name: "Financial scope",
    expanded: true,
    fields: [
      { label: "Price", key: "price", tooltip: "Total project price in GBP." },
      { label: "CapEx available", key: "capexAvailable", tooltip: "Whether capital expenditure financing is available." },
      { label: "CapEx upfront", key: "capexUpfrontGBP", tooltip: "Upfront capital expenditure amount in GBP." },
      { label: "CapEx annual", key: "capexAnnualGBP", tooltip: "Annual capital expenditure payment in GBP." },
      { label: "CapEx min term", key: "capexMinTermYears", tooltip: "Minimum term for capital expenditure agreement in years." },
      { label: "HP available", key: "hpAvailable", tooltip: "Whether Hire Purchase financing is available." },
      { label: "HP upfront", key: "hpUpfrontGBP", tooltip: "Upfront Hire Purchase payment in GBP." },
      { label: "HP annual", key: "hpAnnualGBP", tooltip: "Annual Hire Purchase payment in GBP." },
      { label: "HP term", key: "hpTermYears", tooltip: "Hire Purchase agreement term in years." },
      { label: "PPA available", key: "ppaAvailable", tooltip: "Whether Power Purchase Agreement is available." },
      { label: "PPA upfront", key: "ppaUpfrontGBP", tooltip: "Upfront Power Purchase Agreement payment in GBP." },
      { label: "PPA annual", key: "ppaAnnualGBP", tooltip: "Annual Power Purchase Agreement payment in GBP." },
      { label: "PPA term", key: "ppaTermYears", tooltip: "Power Purchase Agreement term in years." },
    ],
  },
  {
    name: "Speed",
    expanded: true,
    fields: [
      { label: "Lead time", key: "leadTimeWeeks", tooltip: "Number of weeks required before installation can begin." },
      { label: "Installation", key: "installationDays", tooltip: "Number of days required for installation work." },
      { label: "Delivery", key: "deliveryTime", tooltip: "Number of days until project delivery." },
      { label: "Commissioning", key: "commissioningDays", tooltip: "Number of days required for commissioning and testing." },
    ],
  },
  {
    name: "Technical scope",
    expanded: true,
    fields: [
      { label: "Annual output", key: "annualOutputkWh", tooltip: "Expected annual energy output in kilowatt-hours." },
      { label: "Annual consumption", key: "annualConsumptionkWh", tooltip: "Expected annual energy consumption in kilowatt-hours." },
      { label: "Self-sufficiency", key: "selfSufficiencyPercent", tooltip: "Percentage of energy needs met by the system." },
      { label: "Annual export", key: "annualExportkWh", tooltip: "Expected annual energy export to grid in kilowatt-hours." },
      { label: "Panel warranty", key: "panelWarrantyYears", tooltip: "Warranty period for solar panels in years." },
      { label: "Inverter warranty", key: "inverterWarrantyYears", tooltip: "Warranty period for inverters in years." },
      { label: "Workmanship warranty", key: "workmanshipWarrantyYears", tooltip: "Warranty period for workmanship in years." },
      { label: "System lifetime", key: "systemLifetimeYears", tooltip: "Expected system lifetime in years." },
      { label: "Maintenance term", key: "maintenanceTerm", tooltip: "Length of maintenance contract in years." },
      { label: "Maintenance price", key: "maintenancePriceGBP", tooltip: "Annual maintenance price in GBP." },
      { label: "O&M approach", key: "oMApproach", tooltip: "Operations & Maintenance approach and services description." },
    ],
  },
]

const solarFieldExplanations: Record<string, string> = {
  deliveryTime: "Number of days until project delivery.",
  maintenanceTerm: "Length of maintenance contract in years.",
  ppa: "Whether a Power Purchase Agreement is included.",
  leadTimeWeeks: "Number of weeks required before installation can begin.",
  installationDays: "Number of days required for installation work.",
  commissioningDays: "Number of days required for commissioning and testing.",
  capexAvailable: "Whether capital expenditure financing is available.",
  capexUpfrontGBP: "Upfront capital expenditure amount in GBP.",
  capexAnnualGBP: "Annual capital expenditure payment in GBP.",
  capexMinTermYears: "Minimum term for capital expenditure agreement in years.",
  hpAvailable: "Whether Hire Purchase financing is available.",
  hpUpfrontGBP: "Upfront Hire Purchase payment in GBP.",
  hpAnnualGBP: "Annual Hire Purchase payment in GBP.",
  hpTermYears: "Hire Purchase agreement term in years.",
  ppaAvailable: "Whether Power Purchase Agreement is available.",
  ppaUpfrontGBP: "Upfront Power Purchase Agreement payment in GBP.",
  ppaAnnualGBP: "Annual Power Purchase Agreement payment in GBP.",
  ppaTermYears: "Power Purchase Agreement term in years.",
  maintenancePriceGBP: "Annual maintenance price in GBP.",
  oMApproach: "Operations & Maintenance approach and services description.",
  annualOutputkWh: "Expected annual energy output in kilowatt-hours.",
  annualConsumptionkWh: "Expected annual energy consumption in kilowatt-hours.",
  selfSufficiencyPercent: "Percentage of energy needs met by the system.",
  annualExportkWh: "Expected annual energy export to grid in kilowatt-hours.",
  panelWarrantyYears: "Warranty period for solar panels in years.",
  inverterWarrantyYears: "Warranty period for inverters in years.",
  workmanshipWarrantyYears: "Warranty period for workmanship in years.",
  systemLifetimeYears: "Expected system lifetime in years.",
}

const hvacSuppliers: Supplier[] = [
  {
    id: "21",
    name: "HHT Group",
    logo: "/site elements/solar pv logos/HHT Group.png",
    price: 511179.72,
    fields: {
      manufacturer: "Panasonic",
      outdoorUnits: "12",
      totalCostEUR: "511179.72",
      maxCostEUR: "511179.72",
      leadTimeWeeks: "0",
      installationTimeDays: "—",
      materialsEUR: "389513.72",
      labourEUR: "61248",
      electricalEUR: "—",
      maintenanceEUR: "—",
      materialsPercent: "76.2",
      labourPercent: "12",
      costPerOutdoorUnitEUR: "42598",
      costPerIndoorUnitEUR: "2840",
      refrigerant: "R410A",
      lifespanYears: "20",
      workmanshipWarrantyYears: "2",
      equipmentWarrantyYears: "2",
      deliveryTime: "—",
      systemLifespanYears: "20",
    },
    additionalNotes: "",
    keyDifferentiator: "Offers zero lead time (immediate availability) and the highest materials percentage at 76.2%, suggesting they have stock readily available.",
    documents: [
      { name: "Technical spec.pdf", url: "#" },
      { name: "Pricing breakdown.xlsx", url: "#" },
    ],
  },
  {
    id: "22",
    name: "Carraldo Energy",
    logo: "/site elements/solar pv logos/Carraldo Test Supplier.png",
    price: 561601.2,
    fields: {
      manufacturer: "Mitsubishi",
      outdoorUnits: "6",
      totalCostEUR: "561601.2",
      maxCostEUR: "561601.2",
      leadTimeWeeks: "4",
      installationTimeDays: "150",
      materialsEUR: "492896.4",
      labourEUR: "43855",
      electricalEUR: "12450",
      maintenanceEUR: "10800",
      materialsPercent: "87.8",
      labourPercent: "7.8",
      costPerOutdoorUnitEUR: "93600",
      costPerIndoorUnitEUR: "3120",
      refrigerant: "R410A",
      lifespanYears: "20",
      workmanshipWarrantyYears: "4",
      equipmentWarrantyYears: "4",
      deliveryTime: "150",
      systemLifespanYears: "20",
    },
    additionalNotes: "",
    keyDifferentiator: "Provides the longest warranties at 4 years for both workmanship and equipment (double most competitors).",
    documents: [
      { name: "Technical spec.pdf", url: "#" },
      { name: "Pricing breakdown.xlsx", url: "#" },
    ],
  },
  {
    id: "23",
    name: "APN Renewables",
    logo: "/site elements/solar pv logos/APN.png",
    price: 716191.24,
    fields: {
      manufacturer: "Mitsubishi",
      outdoorUnits: "6",
      totalCostEUR: "716191.24",
      maxCostEUR: "716191.24",
      leadTimeWeeks: "3",
      installationTimeDays: "—",
      materialsEUR: "401131.06",
      labourEUR: "99092.5",
      electricalEUR: "39456",
      maintenanceEUR: "25500",
      materialsPercent: "69.2",
      labourPercent: "17.1",
      costPerOutdoorUnitEUR: "119365",
      costPerIndoorUnitEUR: "3979",
      refrigerant: "R32",
      lifespanYears: "20",
      workmanshipWarrantyYears: "2",
      equipmentWarrantyYears: "2",
      deliveryTime: "—",
      systemLifespanYears: "20",
    },
    additionalNotes: "",
    keyDifferentiator: "Uses R32 refrigerant (the only supplier to do so), which is more environmentally friendly with lower global warming potential compared to R410A used by all other bidders.",
    documents: [
      { name: "Technical spec.pdf", url: "#" },
      { name: "Pricing breakdown.xlsx", url: "#" },
    ],
  },
  {
    id: "24",
    name: "Energis GmbH",
    logo: "/site elements/solar pv logos/Energis.png",
    price: 579253.11,
    fields: {
      manufacturer: "Fujitsu",
      outdoorUnits: "6",
      totalCostEUR: "579253.11",
      maxCostEUR: "579253.11",
      leadTimeWeeks: "4",
      installationTimeDays: "42",
      materialsEUR: "434692.8",
      labourEUR: "82380",
      electricalEUR: "2380",
      maintenanceEUR: "14500",
      materialsPercent: "72.4",
      labourPercent: "13.7",
      costPerOutdoorUnitEUR: "96542",
      costPerIndoorUnitEUR: "3218",
      refrigerant: "R410A",
      lifespanYears: "20",
      workmanshipWarrantyYears: "2",
      equipmentWarrantyYears: "5",
      deliveryTime: "42",
      systemLifespanYears: "20",
    },
    additionalNotes: "",
    keyDifferentiator: "Offers the longest equipment warranty at 5 years while maintaining a competitive mid-range price point of €579,253, providing the best equipment protection-to-cost ratio.",
    documents: [
      { name: "Technical spec.pdf", url: "#" },
      { name: "Pricing breakdown.xlsx", url: "#" },
    ],
  },
  {
    id: "25",
    name: "Alterum Partners",
    logo: "/site elements/solar pv logos/Alterum Test Supplier.png",
    price: 599990.8,
    fields: {
      manufacturer: "Mitsubishi Electric",
      outdoorUnits: "12",
      totalCostEUR: "599990.8",
      maxCostEUR: "599990.8",
      leadTimeWeeks: "4",
      installationTimeDays: "30",
      materialsEUR: "—",
      labourEUR: "—",
      electricalEUR: "—",
      maintenanceEUR: "—",
      materialsPercent: "—",
      labourPercent: "—",
      costPerOutdoorUnitEUR: "49999",
      costPerIndoorUnitEUR: "3333",
      refrigerant: "R410A",
      lifespanYears: "15",
      workmanshipWarrantyYears: "2",
      equipmentWarrantyYears: "2",
      deliveryTime: "30",
      systemLifespanYears: "15",
    },
    additionalNotes: "",
    keyDifferentiator: "Achieves the lowest cost for a 12-unit system. However, they specify only a 15-year refrigerant lifespan versus 20 years for competitors.",
    documents: [
      { name: "Technical spec.pdf", url: "#" },
      { name: "Pricing breakdown.xlsx", url: "#" },
    ],
  },
]

const hvacCategories: Category[] = [
  {
    name: "Overview",
    expanded: true,
    fields: [
      { label: "Equipment Manufacturer", key: "manufacturer", tooltip: "Manufacturer of the HVAC equipment." },
      { label: "Outdoor Units", key: "outdoorUnits", tooltip: "Number of outdoor units in the system." },
      { label: "Total Cost", key: "totalCostEUR", tooltip: "Total project cost in Euros." },
      { label: "Max Cost", key: "maxCostEUR", tooltip: "Maximum project cost in Euros." },
      { label: "Lead Time", key: "leadTimeWeeks", tooltip: "Number of weeks required before installation can begin." },
      { label: "Installation Time", key: "installationTimeDays", tooltip: "Number of days required for installation work." },
    ],
  },
  {
    name: "Cost Breakdown",
    expanded: true,
    fields: [
      { label: "Materials", key: "materialsEUR", tooltip: "Cost of materials in Euros." },
      { label: "Labour", key: "labourEUR", tooltip: "Cost of labour in Euros." },
      { label: "Electrical", key: "electricalEUR", tooltip: "Cost of electrical work in Euros." },
      { label: "Maintenance", key: "maintenanceEUR", tooltip: "Cost of maintenance in Euros." },
      { label: "Materials", key: "materialsPercent", tooltip: "Percentage of total cost attributed to materials." },
      { label: "Labour", key: "labourPercent", tooltip: "Percentage of total cost attributed to labour." },
    ],
  },
  {
    name: "Unit Costs",
    expanded: true,
    fields: [
      { label: "Outdoor Units", key: "outdoorUnits", tooltip: "Number of outdoor units in the system." },
      { label: "Total Cost", key: "totalCostEUR", tooltip: "Total project cost in Euros." },
      { label: "Cost per Outdoor Unit", key: "costPerOutdoorUnitEUR", tooltip: "Cost per outdoor unit in Euros." },
      { label: "Cost per Indoor Unit", key: "costPerIndoorUnitEUR", tooltip: "Cost per indoor unit in Euros." },
      { label: "Refrigerant", key: "refrigerant", tooltip: "Type of refrigerant used in the system." },
    ],
  },
  {
    name: "Warranties",
    expanded: true,
    fields: [
      { label: "Lifespan", key: "lifespanYears", tooltip: "Expected operational lifetime of the system in years." },
      { label: "Workmanship Warranty", key: "workmanshipWarrantyYears", tooltip: "Warranty period for workmanship in years." },
      { label: "Equipment Warranty", key: "equipmentWarrantyYears", tooltip: "Warranty period for equipment in years." },
    ],
  },
]

const hvacFieldExplanations: Record<string, string> = {
  manufacturer: "Manufacturer of the HVAC equipment.",
  outdoorUnits: "Number of outdoor units in the system.",
  totalCostEUR: "Total project cost in Euros.",
  maxCostEUR: "Maximum project cost in Euros.",
  leadTimeWeeks: "Number of weeks required before installation can begin.",
  installationTimeDays: "Number of days required for installation work.",
  materialsEUR: "Cost of materials in Euros.",
  labourEUR: "Cost of labour in Euros.",
  electricalEUR: "Cost of electrical work in Euros.",
  maintenanceEUR: "Cost of maintenance in Euros.",
  materialsPercent: "Percentage of total cost attributed to materials.",
  labourPercent: "Percentage of total cost attributed to labour.",
  costPerOutdoorUnitEUR: "Cost per outdoor unit in Euros.",
  costPerIndoorUnitEUR: "Cost per indoor unit in Euros.",
  refrigerant: "Type of refrigerant used in the system.",
  lifespanYears: "Expected operational lifetime of the system in years.",
  workmanshipWarrantyYears: "Warranty period for workmanship in years.",
  equipmentWarrantyYears: "Warranty period for equipment in years.",
  deliveryTime: "Number of days until delivery.",
  systemLifespanYears: "Expected operational lifetime of the HVAC system in years.",
}

export const tenderConfigs: Record<TenderScenario, TenderConfig> = {
  "led": {
    slug: "led",
    title: "LED - Waldemarstraße",
    description: "LED retrofit and controls tender for an occupied office building.",
    location: "Waldemarstraße 57, Berlin, 10997, DE",
    avatar: "/site elements/Avatar.svg",
    tags: ["OCCUPIED", "OFFICE"],
    overview: {
      invited: 10,
      submitted: 4,
      responseRate: 40,
      details: [
        "1 didn't have capacity",
        "2 didn't respond",
        "3 excluded (incomplete pricing)",
        "4 submitted",
      ],
      closedDate: "15 Oct 2025",
      duration: "14 days",
    },
    suppliers: heatPumpSuppliers,
    categories: heatPumpCategories,
    fieldExplanations: heatPumpFieldExplanations,
  },
  "solar-pv": {
    slug: "solar-pv",
    title: "Solar PV - Northampton Corn Exchange",
    description: "1 MW+ rooftop PV tender for a commercial heritage site.",
    location: "4 Market Square, Northampton, NN1 1DE, UK",
    avatar: "/site elements/Avatar.svg",
    tags: ["COMMERCIAL", "+1MW SOLAR"],
    overview: {
      invited: 20,
      submitted: 7,
      responseRate: 35,
      details: [
        "5 didn't respond",
        "4 missed the deadline",
        "3 didn't work on projects of this size",
        "1 excluded (incomplete pricing)",
        "7 submitted",
      ],
      closedDate: "28 Oct 2025",
      duration: "21 days",
    },
    suppliers: solarSuppliers,
    categories: solarCategories,
    fieldExplanations: solarFieldExplanations,
  },
  hvac: {
    slug: "hvac",
    title: "ASHP - Erfstraße 15-20",
    description: "Air-source heat pump upgrade for an occupied hotel asset.",
    location: "Erfstraße 15-20, Köln, 50672, DE",
    avatar: "/site elements/Avatar.svg",
    tags: ["HOTEL", "OCCUPIED"],
    overview: {
      invited: 10,
      submitted: 5,
      responseRate: 50,
      details: [
        "2 didn't respond",
        "3 didn't work on projects of this size",
        "5 submitted",
      ],
      closedDate: "05 Nov 2025",
      duration: "18 days",
    },
    suppliers: hvacSuppliers,
    categories: hvacCategories,
    fieldExplanations: hvacFieldExplanations,
  },
}

export const tenderList = Object.values(tenderConfigs)

export function getTenderConfig(slug: string): TenderConfig | undefined {
  return tenderConfigs[slug as TenderScenario]
}
